/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.icompras2022;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nstuardo
 */
public class detMatriz extends javax.swing.JFrame {
     DefaultTableModel modelo,modelo2;
    /**
     * Creates new form detMatriz
     */
    public detMatriz() {
        initComponents();
        setLocationRelativeTo(null);
        modelo = new DefaultTableModel();
        jTable1.setModel(modelo);

        modelo.addColumn("Cuenta");
        modelo.addColumn("Descripcion");
        String valor=Matriz.jTextField2.getText();
        String valor1=Matriz.jTextField3.getText();
        this.jTextField4.setText(valor);
        this.jTextField1.setText(valor1);
        
        modelo2 = new DefaultTableModel();
        jTable2.setModel(modelo2);
        modelo2.addColumn("Rut");
        modelo2.addColumn("Razon");
        
        llenar1();
        llenar2();
    }
    
    public void llenar1() {

           String query = "select id,ide,cuenta,descripcion from detmatriz WHERE ide="+Matriz.jTextField2.getText();
           cargarDriver();

           //JOptionPane.showMessageDialog(null, cn.ip);
           String dbURL = "";
           Connection dbCon = null;
           Statement stmt = null;
           ResultSet rs = null;
           Conexion cn = new Conexion();
           //String query = "select * from usuarios where usuario='" + tus + "' AND pass='" + pass + "'";

           dbURL = "jdbc:mysql://" + cn.ip + ":3306/" + cn.base;
           String username = cn.usuario;
           String password = cn.pass;
           try {
               dbCon = DriverManager.getConnection(dbURL, username, password);
               stmt = dbCon.prepareStatement(query);
               rs = stmt.executeQuery(query);
           } catch (SQLException ex) {
               //  Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
           }

           try {

            while (rs.next()) {

                Object[] object = new Object[2];
                object[0] = rs.getString(3);
                object[1] = rs.getString(4);
  
                System.out.println("Si");

                modelo.addRow(object);
            }

        } catch (SQLException ex) {
            System.out.println("Nop");
        }

    }

        public void llenar2() {

           String query = "select id,ide,rut,razon from detmatrizpro WHERE ide="+Matriz.jTextField2.getText();
           cargarDriver();

           //JOptionPane.showMessageDialog(null, cn.ip);
           String dbURL = "";
           Connection dbCon = null;
           Statement stmt = null;
           ResultSet rs = null;
           Conexion cn = new Conexion();
           //String query = "select * from usuarios where usuario='" + tus + "' AND pass='" + pass + "'";

           dbURL = "jdbc:mysql://" + cn.ip + ":3306/" + cn.base;
           String username = cn.usuario;
           String password = cn.pass;
           try {
               dbCon = DriverManager.getConnection(dbURL, username, password);
               stmt = dbCon.prepareStatement(query);
               rs = stmt.executeQuery(query);
           } catch (SQLException ex) {
               //  Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
           }

           try {

            while (rs.next()) {

                Object[] object = new Object[2];
                object[0] = rs.getString(3);
                object[1] = rs.getString(4);
  
                System.out.println("Si");

                modelo2.addRow(object);
            }

        } catch (SQLException ex) {
            System.out.println("Nop");
        }

    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();

        setTitle("Comprobante Contable");

        jLabel1.setText("Comprobante");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Grabar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Cuenta");

        jLabel3.setText("Descripcion");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("jLabel4");

        jTextField4.setEditable(false);

        jButton4.setText("-");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Rut", "Razon"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton5.setText("Agregar Proveedor");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jTextField3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton5))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2))
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        SelPlan2 sp;
         try {
             sp = new SelPlan2();
             sp.setVisible(true);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(detMatriz.class.getName()).log(Level.SEVERE, null, ex);
         }
      

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

                Object[] object = new Object[4];
                object[0] = detMatriz.jTextField2.getText();
                object[1] = detMatriz.jTextField3.getText();
          
                modelo.addRow(object);
                limpiar();
                
                
    }//GEN-LAST:event_jButton3ActionPerformed

    
    private void cargarDriver() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (Exception ex) {

        }
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String valor = this.jLabel4.getText();
        if (valor.equals("Nuevo")) {
            cargarDriver();
            Conexion cn = new Conexion();
            String dbURL = "jdbc:mysql://" + cn.ip + ":3306/" + cn.base;
            String username = cn.usuario;
            String password = cn.pass;
            Connection dbCon = null;
            Statement stmt = null;
            ResultSet rs = null;
            int ide = 0;
            try {
                dbCon = DriverManager.getConnection(dbURL, username, password);
                Statement comando = dbCon.createStatement();
                String comprobante = jTextField1.getText();

                comando.executeUpdate("insert into matriz(comprobante) values ('" + comprobante + "')");
                // JOptionPane.showMessageDialog(null, "Comprobante Nuevo Creado");
            } catch (SQLException ex) {
                setTitle(ex.toString());
            }

            //
            String cuenta;
            String descripcion;

            for (int i = 0; i < jTable1.getRowCount(); i++) {
                cuenta = jTable1.getValueAt(i, 0).toString();
                descripcion = jTable1.getValueAt(i, 1).toString();

                try {
                    dbCon = DriverManager.getConnection(dbURL, username, password);
                    Statement comando = dbCon.createStatement();

                    //last
                    String query = "SELECT MAX(id) FROM matriz";
                    cargarDriver();
                    dbURL = "jdbc:mysql://" + cn.ip + ":3306/" + cn.base;
                    username = cn.usuario;
                    password = cn.pass;
                    try {
                        dbCon = DriverManager.getConnection(dbURL, username, password);
                        stmt = dbCon.prepareStatement(query);
                        rs = stmt.executeQuery(query);
                    } catch (SQLException ex) {
                        //  Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    try {
                        while (rs.next()) {
                            ide = rs.getInt(1);
                        }
                    } catch (SQLException ex) {
                        System.out.println("Nop");
                    }

                    //fin last
                    comando.executeUpdate("insert into detmatriz(ide,cuenta,descripcion) values (" + ide + ",'" + cuenta + "','" + descripcion + "')");

                } catch (SQLException ex) {
                    setTitle(ex.toString());
                }

            }
            
            //grabar tabla proveedores
            String rut;
            String razon;

            for (int i = 0; i < jTable2.getRowCount(); i++) {
                rut = jTable2.getValueAt(i, 0).toString();
                razon = jTable2.getValueAt(i, 1).toString();

                try {
                    dbCon = DriverManager.getConnection(dbURL, username, password);
                    Statement comando = dbCon.createStatement();

                 
                    comando.executeUpdate("insert into detmatrizpro(ide,rut,razon) values (" +this.jTextField4.getText() + ",'" + rut + "','" + razon + "')");

                } catch (SQLException ex) {
                    setTitle(ex.toString());
                }

            }
            //fin grabar Tabla
            

            //
            JOptionPane.showMessageDialog(null, "Comprobante Nuevo Creado");

        }
        
        if (valor.equals("Editar")) {
            
             cargarDriver();
            Conexion cn = new Conexion();
            String dbURL = "jdbc:mysql://" + cn.ip + ":3306/" + cn.base;
            String username = cn.usuario;
            String password = cn.pass;
            Connection dbCon = null;
            Statement stmt = null;
            ResultSet rs = null;
            int ide = 0;
            try {
                dbCon = DriverManager.getConnection(dbURL, username, password);
                Statement comando = dbCon.createStatement();
                String comprobante = jTextField1.getText();

                comando.executeUpdate("UPDATE matriz SET comprobante='" + comprobante + "' WHERE id="+this.jTextField4.getText());
                // JOptionPane.showMessageDialog(null, "Comprobante Nuevo Creado");
            } catch (SQLException ex) {
                setTitle(ex.toString());
            }
            
            //borrar tabla
              try {
                dbCon = DriverManager.getConnection(dbURL, username, password);
                Statement comando = dbCon.createStatement();
                String comprobante = jTextField1.getText();

                comando.executeUpdate("DELETE FROM  detmatriz WHERE ide="+this.jTextField4.getText());
                comando.executeUpdate("DELETE FROM  detmatrizpro WHERE ide="+this.jTextField4.getText());
                // JOptionPane.showMessageDialog(null, "Comprobante Nuevo Creado");
            } catch (SQLException ex) {
                setTitle(ex.toString());
            }
            
            //fin borrar tabla
            
            //grabar Tabla
                    //
            String cuenta;
            String descripcion;

            for (int i = 0; i < jTable1.getRowCount(); i++) {
                cuenta = jTable1.getValueAt(i, 0).toString();
                descripcion = jTable1.getValueAt(i, 1).toString();

                try {
                    dbCon = DriverManager.getConnection(dbURL, username, password);
                    Statement comando = dbCon.createStatement();

                 
                    comando.executeUpdate("insert into detmatriz(ide,cuenta,descripcion) values (" +this.jTextField4.getText() + ",'" + cuenta + "','" + descripcion + "')");

                } catch (SQLException ex) {
                    setTitle(ex.toString());
                }

            }
            //fin grabar Tabla
            
                  //grabar Tabla
                    //
            String rut;
            String razon;

            for (int i = 0; i < jTable2.getRowCount(); i++) {
                rut = jTable2.getValueAt(i, 0).toString();
                razon = jTable2.getValueAt(i, 1).toString();

                try {
                    dbCon = DriverManager.getConnection(dbURL, username, password);
                    Statement comando = dbCon.createStatement();

                 
                    comando.executeUpdate("insert into detmatrizpro(ide,rut,razon) values (" +this.jTextField4.getText() + ",'" + rut + "','" + razon + "')");

                } catch (SQLException ex) {
                    setTitle(ex.toString());
                }

            }
            //fin grabar Tabla
            
            
            JOptionPane.showMessageDialog(null, "Comprobante Editado");
        }
           
             Matriz ma=new Matriz(this,true);
             ma.llenar1();
             this.dispose();
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel(); //TableProducto es el nombre de mi tabla ;) 
        dtm.removeRow(jTable1.getSelectedRow());

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
                Object[] object = new Object[2];
                object[0] = this.jTextField5.getText();
                object[1] = this.jTextField6.getText();

                modelo2.addRow(object);
                this.jTextField5.setText("");
                this.jTextField6.setText("");

    }//GEN-LAST:event_jButton5ActionPerformed
  
    public void limpiar(){
       detMatriz.jTextField2.setText("");
       detMatriz.jTextField3.setText("");      
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detMatriz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
